In [ ]:
import pandas as pd



import numpy as numpy

from sklearn.preprocessing import scale
from sklearn.decomposition import PCA

import scipy

import sklearn

In [ ]:
data = pd.read_csv('drive/My Drive/development/MachineLearning/b5.csv')



# convert data to  numpy array

X = data.values
print(X)




Y = scale(X)
Y[:10]
#print(X)



 #X.write_csv(drive/My Drive/development/MachineLearning/b.csv')




[[4 2 5 ... 2 5 5]
 [2 2 3 ... 1 3 2]
 [5 1 1 ... 5 5 5]
 ...
 [2 5 4 ... 5 5 5]
 [1 4 2 ... 3 5 5]
 [2 3 1 ... 5 5 5]]


array([[ 1.112632  , -0.57855181,  1.28086553, -0.94276992,  1.22252056,
        -1.16953421,  0.78985547, -0.29758441,  1.36682942, -1.98444433,
        -1.72867883,  1.49804199, -1.61774948,  1.83712728, -1.53260415,
        -1.49914441, -1.65576384, -1.33471187, -1.64016834, -1.39611721,
        -0.95769369,  0.99437247, -0.95818139,  0.92691041, -0.14278856,
        -0.79072448, -1.02395628,  1.19139931,  0.0528502 ,  1.25475131,
         0.62003083, -1.45260443,  1.01461041, -1.33544952,  1.84717327,
        -1.37736855,  0.30760221, -1.31084069,  0.62458817,  1.34908527,
         0.27289598, -1.01300101, -1.12035743, -0.97038162,  1.19909704,
        -0.74377116, -0.08171344, -0.96448433,  0.88177594,  1.0099427 ],
       [-0.51209309, -0.57855181, -0.33817724, -0.12437974, -0.33803874,
         0.442706  , -1.30709615,  1.28346328, -1.49931081,  1.08607746,
        -0.96435197, -0.20146268,  0.13841508, -0.61776479,  0.03936142,
         0.77443384, -0.11655842, -0.59418326, -0.

In [ ]:
pca = PCA()

pca.fit(Y)

print(pca.explained_variance_ratio_)

[0.16101911 0.09246263 0.07527279 0.07100381 0.05526279 0.0313044
 0.02660753 0.02099101 0.01937029 0.01849593 0.01794133 0.01735232
 0.01689316 0.01604282 0.01576013 0.01470117 0.01459846 0.01438242
 0.01362569 0.01322527 0.0131285  0.01268631 0.01223362 0.01180048
 0.01164071 0.01136677 0.01108761 0.0106515  0.01045028 0.0102118
 0.01003675 0.00983507 0.00974897 0.00963948 0.0089566  0.00894
 0.00868373 0.00840808 0.00831106 0.00808253 0.00793945 0.00760062
 0.00748126 0.00727417 0.00694749 0.00689884 0.00650197 0.00647554
 0.0062404  0.00442735]


In [ ]:
pca5 = PCA(n_components=5)

pca5.fit(X)

print(pca5.explained_variance_ratio_)

[0.1732156  0.10143878 0.07428048 0.05942256 0.05669855]


In [ ]:
print(pca5.components_)


[[-1.87186560e-01  1.95215398e-01 -2.52861204e-01  2.11892516e-01
  -2.40797461e-01  1.95787989e-01 -2.63458882e-01  1.44217051e-01
  -1.92918979e-01  2.23369035e-01  1.79005665e-01 -1.29474569e-01
   1.27827138e-01 -1.09218923e-01  1.54855239e-01  1.94565482e-01
   1.85861435e-01  2.05902892e-01  1.97843113e-01  2.22840345e-01
   9.12160602e-02 -1.40212351e-01  9.04020324e-02 -7.59439039e-02
   1.05808240e-01 -3.33483706e-02  1.57712148e-01 -9.40225839e-02
  -8.29728892e-02 -1.47220554e-01 -9.09623716e-02  6.07971793e-02
  -4.61235043e-02  1.56143088e-01 -1.07333482e-01  1.10004293e-01
  -3.44681142e-02  1.22281757e-01 -8.56693083e-02 -6.50912503e-02
  -4.95062812e-02  7.93506556e-02 -1.32455194e-02  5.18853869e-02
  -8.41229322e-02  6.10022567e-02 -7.02531940e-02  3.07212401e-04
   1.82673931e-02 -7.56865062e-02]
 [-1.78881262e-01  2.27309414e-01 -1.07447847e-01  1.49469239e-01
  -1.94896597e-01  1.60135482e-01 -2.17627054e-01  1.67705741e-01
  -1.97473614e-01  1.37176341e-01 -2.0667

In [ ]:

from matplotlib import pyplot as pyplot


!pip install scipy
import scipy

#from scipy.cluster.hierarchy import dendogram, linkage



#import scipy.cluster.hierarchy.dendrogram
states = pd.read_csv('drive/My Drive/development/MachineLearning/ClusterData.csv')



list(states.columns.values)

['State',
 'state_code',
 'data science',
 'cluster analysis',
 'college',
 'startup',
 'entrepreneur',
 'ceo',
 'mortgage',
 'nba',
 'nfl',
 'mlb',
 'fifa',
 'modern dance',
 'prius',
 'escalade',
 'subaru',
 'jello',
 'bbq',
 'royal family',
 'obfuscation',
 'unicorn',
 'Extraversion',
 'Agreeableness',
 'Conscientiousness',
 'Neuroticism',
 'Openness',
 'PsychRegions',
 'region',
 'division']

In [ ]:
import sklearn


import pylab as pl




from sklearn.neighbors import KNeighborsClassifier

In [ ]:
ccdefault = pd.read_csv("drive/My Drive/development/MachineLearning/ccdefault.csv")






In [ ]:
 list(ccdefault.columns.values)

ccd = ccdefault[ccdefault.columns[1:]]

list(ccd.columns.values)


['LIMIT_BAL',
 'SEX',
 'EDUCATION',
 'MARRIAGE',
 'AGE',
 'PAY_0',
 'PAY_2',
 'PAY_3',
 'PAY_4',
 'PAY_5',
 'PAY_6',
 'BILL_AMT1',
 'BILL_AMT2',
 'BILL_AMT3',
 'BILL_AMT4',
 'BILL_AMT5',
 'BILL_AMT6',
 'PAY_AMT1',
 'PAY_AMT2',
 'PAY_AMT3',
 'PAY_AMT4',
 'PAY_AMT5',
 'PAY_AMT6',
 'DEFAULT']

In [ ]:
import numpy as np

test_idx =  np.random.uniform(0,1,len(ccd)) <=0.33
                          
train =ccd[test_idx == True]

test = ccd[test_idx == False]

train.head()


feature = ['LIMIT_BAL', \
 'SEX',\
 'EDUCATION',\
 'MARRIAGE',\
 'AGE',\
 'PAY_0',\
 'PAY_2',\
 'PAY_3',\
 'PAY_4',\
 'PAY_5',\
 'PAY_6',\
 'BILL_AMT1',\
 'BILL_AMT2',\
 'BILL_AMT3',\
 'BILL_AMT4',\
 'BILL_AMT5',\
 'BILL_AMT6',\
 'PAY_AMT1',\
 'PAY_AMT2',\
 'PAY_AMT3',\
 'PAY_AMT4',\
 'PAY_AMT5',\
 'PAY_AMT6',\
 'DEFAULT']

In [ ]:


n = 5

results = []

clf = KNeighborsClassifier(n_neighbors=n)

clf.fit(train[feature], train['DEFAULT'])
        

preds = clf.predict(test[feature])


accuracy = np.where(preds == test['DEFAULT'], 1, 0 ).sum() / float(len(test))*100

print(accuracy)

74.68404816399642
